version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/main
    restart: unless-stopped
    env_file:
      - .env.core
      - .env.overlay
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${OTEL_PROMETHEUS_EXPORTER_API_PORT}:9464"
    networks:
      - default
    depends_on:
      toxiproxy:
        condition: service_healthy
    profiles:
      - core

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/worker
    restart: unless-stopped
    env_file:
      - .env.core
      - .env.overlay
    ports:
      - "${OTEL_PROMETHEUS_EXPORTER_WORKER_PORT}:9465"
    networks:
      - default
    depends_on:
      toxiproxy:
        condition: service_healthy
    profiles:
      - core

  toxiproxy:
    container_name: toxiproxy
    build: ./toxiproxy
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "8474:8474"
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [
          "CMD-SHELL",
          'curl -sf http://localhost:8474/proxies | grep -q "postgres" &&
          curl -sf http://localhost:8474/proxies | grep -q "redis" &&
          curl -sf http://localhost:8474/proxies | grep -q "rabbitmq"',
        ]
      interval: 5s
      timeout: 3s
      retries: 30
    profiles:
      - deps

  # Uncomment if you want to use MongoDB
  # mongo:
  #   image: mongo:7
  #   container_name: mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_DB}
  #   volumes:
  #     - mongo_data:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - default
  #   profiles:
  #     - deps

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 30
    profiles:
      - deps

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
    profiles:
      - deps

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_METRICS_PORT}:15692"
    networks:
      - default
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 30
    profiles:
      - deps

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    container_name: otel-collector
    restart: unless-stopped
    command:
      [
        "--config=/etc/otel/config.yml",
        "--feature-gates=-component.UseLocalHostAsDefaultHost",
      ]
    volumes:
      - ./telemetry/volumes/static/otel-collector-config.yml:/etc/otel/config.yml
    ports:
      - "${OTEL_HTTP_PORT}:4318"
      - "${OTEL_GRPC_PORT}:4317"
    networks:
      - default
    depends_on:
      - jaeger
    profiles:
      - telemetry

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "${JAEGER_PORT}:16686"
    networks:
      - default
    profiles:
      - telemetry

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    container_name: postgres-exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - telemetry

  # Uncomment if you want to use MongoDB
  # mongodb-exporter:
  #   image: percona/mongodb_exporter:0.47.1
  #   container_name: mongo-exporter
  #   command:
  #     - "--mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/admin?sslmode=disable"
  #   restart: unless-stopped
  #   ports:
  #     - "9216:9216"
  #   networks:
  #     - default
  #   depends_on:
  #     - mongo
  #   profiles:
  #     - telemetry

  redis-exporter:
    image: oliver006/redis_exporter:v1.61.0
    container_name: redis-exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_EXPORTER_INCL_SYSTEM_METRICS=true
      - REDIS_EXPORTER_INCL_COMMAND_STATS=true
      - REDIS_EXPORTER_INCL_LATENCY_METRICS=true
    ports:
      - "9121:9121"
    networks:
      - default
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - telemetry

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=otlp-write-receive
      - --web.enable-remote-write-receiver
    volumes:
      - ./telemetry/volumes/generated/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - default
    depends_on:
      - postgres-exporter
      # - mongodb-exporter # Uncomment if you want to use MongoDB
      - redis-exporter
    profiles:
      - telemetry

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./telemetry/volumes/static/grafana/provisioning:/etc/grafana/provisioning
      - ./telemetry/volumes/static/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "${GF_PORT}:3000"
    networks:
      - default
    depends_on:
      - prometheus
      - jaeger
    profiles:
      - telemetry

  k6:
    image: grafana/k6:1.4.0
    container_name: k6
    command: run -o experimental-prometheus-rw /test/main.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - BASE_URL=${BASE_URL}
      - VIRTUAL_USER_COUNT=${VIRTUAL_USER_COUNT}
      - TEST_DURATION=${TEST_DURATION}
    volumes:
      - ./test/k6:/test
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
    profiles:
      - testing

volumes:
  mongo_data:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge
