apiVersion: 1
groups:
    - orgId: 1
      name: health
      folder: backend
      interval: 1m
      rules:
        - uid: cf4fqiboycjk0c
          title: API process down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                exemplar: false
                expr: up{job="api"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 5000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: Alerting
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: api
            severity: critical
          isPaused: false
        - uid: ff4fsuu1oqcxsc
          title: Worker process down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                exemplar: false
                expr: up{job="worker"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 5000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: Alerting
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: worker
            severity: critical
          isPaused: false
    - orgId: 1
      name: reliability
      folder: backend
      interval: 5m
      rules:
        - uid: df4fwuraqcjk0e
          title: HTTP 5xx error ratio high
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: sum(rate(http_server_duration_count{http_status_code=~"5.."}[1m])) / sum(rate(http_server_duration_count[1m]))
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.05
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations: {}
          labels:
            service: api
            severity: warning
          isPaused: false
    - orgId: 1
      name: health
      folder: dependencies
      interval: 1m
      rules:
        - uid: cf4ftan62w2rkd
          title: Postgres process down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                exemplar: false
                expr: pg_up
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 5000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: Alerting
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: postgres
            severity: critical
          isPaused: false
        - uid: cf4ftdlau2v40b
          title: Redis process down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                exemplar: false
                expr: redis_up
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 5000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: Alerting
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: redis
            severity: critical
          isPaused: false
        - uid: ef4ftn95322gwf
          title: RabbitMQ process down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                exemplar: false
                expr: up{job="rabbitmq"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 5000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: Alerting
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: rabbitmq
            severity: critical
          isPaused: false
        - uid: ef4fxjncc3g1sf
          title: Postgres circuit open
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: circuit_breaker_state{dependency="postgresql"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: postgres
            severity: critical
          isPaused: false
        - uid: ff4fxrp9xbapsb
          title: Redis circuit open
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: circuit_breaker_state{dependency="redis"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: redis
            severity: critical
          isPaused: false
        - uid: ef4fxw426g934b
          title: RabbitMQ circuit open
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: circuit_breaker_state{dependency="rabbitmq"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: {}
          labels:
            service: redis
            severity: critical
          isPaused: false
